export const TYPES= {
    ADD_TO_CART: "ADD_TO-CART",
    REMOVE_ONE_FROM_CART: "REMOVE_ONE_ROM_CART",
    REMOVE_ALL_FROM_CART: "REMOVER_ALL_FROM_CART",
    CLEAR_CART: "CLEAR_CART",
    CREATE_LIST:"CREATE_LIST",

}